### ISSUE TITLE
markers_to_makefile fails when camera latency is "auto"

### ISSUE THREAD

**Issue by rpet** [ltratt/aeschylus#2]
`markers_to_makefile` fails when the parameter for the camera latency is set to "auto".

The culprit seems to be the conversion to `int` of the parameter `sys.argv[2]` at line 174 in this section:

```
    if sys.argv[2] == "auto":
        start_time = times[0]
        audio_off = times[1] - times[0]
        screen_off = (int(sys.argv[2]) + (times[2] - times[1])) / 1000.0
        delay = 0
```
Doing a comparison with the `else` section, I guess that `screen_off` shoud be calculated this way:

```
        screen_off = (audio_off+(times[2] - times[1])) / 1000.0
```
but it is only a fast patch to get rid of the error.

**Comment by ltratt** [comment]
As you've possibly realised, `screen_off` was added after the last time I tested the `auto` setting -- sorry! I *think* the fix in https://github.com/ltratt/aeschylus/commit/a20e5be443ab2a272c09b1e1b138cdb7f5d7324d might be correct. At the very least it should not cause the dynamic type error you're seeing!
